### ISSUE TITLE
Help with expected input

### ISSUE THREAD

**Issue by kvittingseerup** [Danko-Lab/TED#1]
Thanks for providing this tool - it looks extremely promising. 

I have a couple of clarifying questions:

1. When having data from multiple patients you suggest collapsing cell types per patient. Does that mean the `input.phi` matrix given to `run.Ted` have X reference rows where X = p * c (and p= number of patients, and c = number of celltypes)?
2. Could you give examples run times for some of the deconvolutions you have done for the paper? Just so we have a ballpark number of what to expect.
3. Is there are minimum number of bulk samples required to deconvolute? Can TED deconvolute fx 6 samples (a 3x2 experiment)?

Cheers
Kristoffer

**Comment by tinyi** [comment]
Dear Kristoffer,

Thank you very much for your interest in our work. Here are the answers to
your questions.

1. In general we recommend users to collapse the tumor cells in each
patient, while collapsing non-malignant cells across all patients. For
example, the refGBM8 used in our paper has   Patient-1-Tumor-subcluster1
,..., Patient-8-Tumor-subclusterN (60 tumor subclusters from 8 patients),
pericytes, endothelial, T cell, macrophage, oligodendrocytes (5
non-malignant cells across all patients). If there is substantial
heterogeneities in the non-malignant cells, one should treat each
cluster of non-malignant cell separately.

2. See attached pdf.

3. No minimum required. TED assumes the tumor expression in each sample is
conditional independent (conditional on input.phi).

Hope this helps.

Best,

Tinyi

**Comment by kvittingseerup** [comment]
Hi Tinyi

Thanks for the quick answer!

With regards to 2: I don't think the attachment was transfered to github?

With regards to 3: Did you experiment with information sharing across bulk samples - does not seem a stretch to assume the the different cell types exist in somewhat same proportions in a cohort of bulk patients?

**Comment by tinyi** [comment]
Dear Kristoffer,

I have just added the runtime to the github repository. Kindly check it
out.

TED does not assume similar cell type proportion across bulk samples, which
is often not the case in TCGA samples due to the heterogeneity of the tumor
microenvironment. In fact, the posterior of the cell type fraction is so
strong, and is sufficiently driven by the mixture samples themselves.

TED does however assumes the non-malignant cells have the same expression
across bulk samples. This piece of shared information is used to update the
initial estimates of cell type fraction.

Hope this answers your question.

Best,

Tinyi

**Comment by kvittingseerup** [comment]
Beautiful! That is a very nice idea of sharing only the normal cells.

Impressive runtimes!

Thanks!

**Comment by tinyi** [comment]
Dear Kristoffer,

A vignette has now been included in the github. Also, I have updated the
run.Ted function so that it will now automatically collapse, align the
genes on the common subset between reference and bulk, and normalized the
scRNA-seq reference.

Best,

Tinyi

**Comment by kvittingseerup** [comment]
Thanks! :D
